name: pagseguro_smart_flutter
description: Integre o Flutter com maquinas smarts da Pagseguro, utilizando o SDK do Pagseguro. Rápido e fácil.
version: 1.2.0
repository: https://github.com/gabuldev/pagseguro_smart_flutter

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.gabul.pagseguro_smart_flutter
        pluginClass: PagseguroSmartFlutterPlugin
      ios:
        pluginClass: PagseguroSmartFlutterPlugin
